### ISSUE TITLE
Add support for reading/writing `f32` / `f64`

### ISSUE THREAD

**Issue by sdroege** [tuffy/bitstream-io#13]
This would require implementing the `Numeric` trait for them, but that's not possible right now because the trait is too specific. It should probably be split up into a simpler trait for the `ByteReader`/etc and the huffman/etc types should work with a supertrait that adds the additional requirements.

**Comment by tuffy** [comment]
I've pushed out a version 1.8 with fresh support for `f32`/`f64` via `read_to` and `write_from` methods which work on a `Primitive` trait (split out from `Numeric`) for handling types with fixed sizes but potentially multiple endianness representations.

This doesn't help much for the Huffman handlers (due to that extra context they require).  But a trivial blanket implementation for byte arrays does obsolete the `read_to_array` methods, and they've now been marked deprecated.

**Comment by sdroege** [comment]
Nice, thanks :)
